version: '3.7'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ssafy
      MYSQL_DATABASE: characterlit
      MYSQL_USER: root
      MYSQL_PASSWORD: ssafy
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
      
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: guest
      MONGO_INITDB_ROOT_PASSWORD: guest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db