version: '3'

services:
  springboot:
    image: my-springboot-image:latest
    container_name: springboot_container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672

  vue:
    image: my-vue-image:latest
    container_name: vue_container
    restart: always
    ports:
      - "80:80"

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq_container
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest