version: '3.7'

services:
  springboot:
    image: woojincheon/spring:latest
    container_name: spring
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672

  vue:
    image: woojincheon/front:latest
    container_name: front
    restart: always
    ports:
      - "80:80"

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest